# Generated by Django 4.2.1 on 2023-05-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Midias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('director', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateField()),
            ],
        ),
    ]
