# Generated by Django 4.2.1 on 2023-05-03 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('midias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='midias',
            options={'verbose_name_plural': 'Midias'},
        ),
    ]
